# Application Configuration
spring.application.name=student-management
server.port=8080

# Désactiver JPA/Hibernate pour éviter l'erreur de connexion DB
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.show-sql=false

# Logger configuration
logging.level.root=WARN
logging.level.tn.esprit=INFO
